apiVersion: v1
kind: Namespace
metadata:
  name: user-system
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: user-system
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: mysecretpassword
  POSTGRES_DB: project_db
